### ISSUE TITLE
Is it compatible with Zijiang POS58 thermal printer?

### ISSUE THREAD

**Issue by XAS-712** [klirichek/zj-58#14]
I have got a Zijiang POS58 thermal printer and I want to use it on an ARM platform based computer, Raspberry Pi 3. I connected it to my RPi, but it cannot print anything.

**Comment by klirichek** [comment]
It might be, you can give a try!
I have two different models - one 'xp-58', which is kind of 'xprinter'. Second is 'zijiang'.
The filter was reconstructed and tested for second one, however when looking to filters they are very similar. I even think to make universal binary for both.

If you tried compiled binary here it surely will not work on raspberry, since it is compiled for x64 intel. So, for arm you need to recompile it.

**Comment by XAS-712** [comment]
Now it probably works, but it just feeds paper and don't print anything.

**Comment by bot9987** [comment]
i have the same problem. After your help in compiling for OSX I've created a new CUPS printer. The printer does not print anything from the system itself only feed one line of paper when the job start and one line when the job ends. 
I found out It does however print the CUPS test page with no problem. Also this test pdf: http://zsory-furdo.hu/evcms_medias/upload/files/testfile.pdf
So i guess it is something in preparing the file the right way to make it work. I will let you know what I find.

**Comment by bot9987** [comment]
got it to work. just save your file as a postscript level3 file. it prints perfectly.

**Comment by klirichek** [comment]
That is not a problem of a filter. It just do nothing with any level of PS or PDF.
Cups creates a chain of the filters to achieve result. So, say, when you print a plain text - it first changed into 'ps' or 'pdf', then rastered into 'cups-raster', and finally the filter takes 'cups-raster' and finally produces low-level commands for printing systematized as 'vendor-raster'.
You need whole chain to be available in order to make it working. Investigation of cups logs usually helps in case of problems.
