### ISSUE TITLE
pulled the new git installed not working at all

### ISSUE THREAD

**Issue by Boby** [klirichek/zj-58#24]
Hi,

I used the tutorial and run the install through rpi, and cmake are not available, make are not even working at all and I decided to run it manually :

/etc/init.d/cups stop
cp rastertozj /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp ZJ-58.ppd /usr/share/cups/model/zjiang/
cd /usr/lib/cups/filter
chmod 755 rastertozj
chown root:root rastertozj
cd -
/etc/init.d/cups start

but the files are different : 

it dont have rastertozj but instead its rasterozj.c and there are no zj-58.ppd but its zj58.ppd

and I tried modifying it manually but the printer was detected under unknown printer : SMT32

and was not able to print at all but when using the echo via command line it was able to print

thank you

**Comment by klirichek** [comment]
`rastertozj.c` is not the filter, it will NOT work. It is source file and NEED to be compiled for your platform using gcc or clang. And `cmake` is just the tool which glues whole recipe together, as compiling filter, compiling ppd driver, and installing all together.

Printer ID is provided by (surprise!) printer itself by wire. Since many of cheap chinese printers have different mass of such ids (mine, for example, report itself as 'IEEE_1284_Controlle'), I see no reason to try to catch and them into ppd, so just convenient 'zj-58' is placed there instead.

So, your approach by 'I've copied something somewhere and it doesn't work' is not at all the way it has to be called 'installed'.

**Comment by Boby** [comment]
any method should I use? as I cant run cmake or make somehow, sorry still very noob at this

**Comment by klirichek** [comment]
cmake is available on rpi, something about v3.02 from repo.
So, mentioned 
```
sudo apt install build-essential cmake libcups2-dev libcupsimage2-dev
```
works and installs required prerequisites.

**Comment by Boby** [comment]
let me give it a shot tonight!

**Comment by Boby** [comment]
Hi Klirichek,

run the command :


Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
cmake is already the newest version (3.7.2-1).
libcups2-dev is already the newest version (2.2.1-8+deb9u2).
libcupsimage2-dev is already the newest version (2.2.1-8+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


and turns out its already done, but still somehow running cmake are not working

**Comment by Boby** [comment]
oops sorry I tried this :

cmake zj-58/
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Cups: /usr/lib/arm-linux-gnueabihf/libcups.so (found version "2.2.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi

**Comment by Boby** [comment]
turns out after running the commands cmake and sudo install, it installed correctly now! once again thank you @klirichek
