### ISSUE TITLE
A few unwanted / unreadable characters on the header

### ISSUE THREAD

**Issue by darkterra** [klirichek/zj-58#3]
I buy a Excelvan POS-58 for 46€ (I know, is not the zj-58 printer :)).

On the site where I bought it, they said there were drivers for windows, mac, linux, etc. Only, there was only drivers for window.

So I search ont the wev, and I found the article scruss http://scruss.com/blog/2015/07/12/thermal-printer-driver-for-cups-linux-and-raspberry-pi-zj-58

This driver work properly with this printer on a Raspberry PI (and CUPS). But when I print (a generated pdf file) for a reason that an Escape me I have sometimes a few unwanted / unreadable characters that are added on top of the ticket (see: https://goo.gl/photos/W6dxGT7BgShz4wGP8)

The lines ” DarkTerra ” repeated is normal, I was just too lazy to write something different for each line.

I'm pretty sure the PDF file is not causing the problem.

Finally, I decided to watch the rastertozj.c code, and I see that we can activate the verbose mode. So, I uncommented the line ' #define DEBUGP ' I launch a new make then sudo ./install

I print a page, and unfortunately I can not find anything in /tmp

I'm not likely familiar with make, I may have missed a step ?

Knowing that the driver was already installed without changes

Other info, if I turn off and I turn on the printer between each print, I never have these unwanted / unreadable characters

So I guess the printer keeps in its memory information / junk from the previous print characters.

A workaround would be to flush the memory before (or after) each impression.

An idea about my problems undesirable characters ?
How else can I do an uninstall and reinstall the driver with own verbose mode enabled?

thank you in advance

**Comment by mike42** [comment]
Starting each print with "ESC @" (initialize) and finishing it with a newline (empty buffer) would be a sensible way to address this in the filter in my opinion.

Your analysis is correct, you do need an empty print buffer before you can send an image. The first line of the output could be getting corrupted because some other command has already started the line.

**Comment by darkterra** [comment]
Thank @mike42 for your response !

Ok so, I think I can modifie the original code of 'rastertozj.c' file like this:

```c
// sent on the beginning of print job
void jobSetup()
{
	// Add 'ESC @' to Flush
	mputchar(0x1B);
	mputchar(0x40);

	if ( settings.cashDrawer1==1 )
		outputCommand(cashDrawerEject[0]);
	if ( settings.cashDrawer2==1 )
		outputCommand(cashDrawerEject[1]);
	outputCommand(printerInitializeCommand);
}

// sent at the very end of print job
void ShutDown()
{
	// Add 'LF' => Empty buffer
	mputchar(0x0A);

	if ( settings.cashDrawer1==2 )
		outputCommand(cashDrawerEject[0]);
	if ( settings.cashDrawer2==2 )
		outputCommand(cashDrawerEject[1]);
	outputCommand(printerInitializeCommand);
}
```

I try today !

**Comment by darkterra** [comment]
I,

I try the snippet, but doesen't work for me -_-.

Maybe the problem come from CUPS ?

**Comment by mike42** [comment]
Perhaps you would be to able to post some binary output that shows the issue? You can run CUPS filters directly, or set up a print queue that outputs [to a file](https://wiki.linuxfoundation.org/en/OpenPrinting/Database/CupsFAQ#How_do_I_print_to_a_file.3F).

**Comment by darkterra** [comment]
Thank you for your quick reply, I try tonight (French time)

**Comment by darkterra** [comment]
I know only little CUPS, but it seems that it have changed.
See this link [cups-files.conf](https://www.cups.org/doc/man-cups-files.conf.html)

_FileDevice Yes
FileDevice No
Specifies whether the file pseudo-device can be used for new printer queues. The URI "file:///dev/null" is always allowed._

**Comment by XAS-712** [comment]
I have a POS58 printer too. But my printer cannot print anything.

**Comment by klirichek** [comment]
It may be bug with raster calculation.
When printing height is not order of 24 lines, it was a bug and this rest chunk wasn't printed.
So, it may be that raster header is pushed, but not enough data is feeded to the printer.
Next print will first fulfill that buffer with own data, but the tail of it is just a piece of raster garbage not intended to be print in text mode, and it is revealed.
This issue was fixed, however, you may try.

**Comment by mozzie** [comment]
I ran to the same unwanted characters issue while printing jpegs to a POS58 printer. I don't know what causes it, but trial and error lead me to finding Scale-to-fit caused these problems. I resized my images to match the width of the tape and lenghtened the page height. Problem removed.

**Comment by LukePrior** [comment]
Did anyone manage to resolve this?

**Comment by ganzgustav22** [comment]
I have the same issue. What I could find out so far: 
- It happens when printing a small .txt file
- It happens when printing the same txt file converted to .png with imagemagick convert

- However, it doesn't happen when printing a somewhat larger .png (46kbytes)


In general, the zj-58 drivers seem to be fine, I have printed thousands of printouts with dozens of printers just fine, rock-solid always works 100%. 

Just with this this different printer model now these issues occur.
